name: AdminCmd
main: com.Balor.bukkit.AdminCmd.AdminCmd
version: 4.6
author: Plague modded by Balor
description: >
             This plugin implements the basic commands for running a server.
commands:
  bal_timeset:
    description: Set world time to a given timestamp/alias.
    aliases: time
    usage: /<command> day|night|dusk|dawn|<raw>
  bal_timeday:
    description: Short for /time day.
    aliases: day
    usage: /<command>
  bal_playerlist:
    description: Lists all online players.
    aliases: [playerlist,plist,who]
    usage: /<command>
  bal_playerheal:
    description: Heal the player.
    aliases: [pheal,heal]
    usage: /<command> (|playername)
  bal_playerkill:
    description: kill the player.
    aliases: [pkill,kill]
    usage: /<command> (|playername)
  bal_repair:
    description: Repair if possible the item in hand.
    aliases: [repair,rep]
    usage: /<command>
  bal_repairall:
    description: Repair if possible the item in hand.
    aliases: [repairall,repa]
    usage: /<command>
  bal_playerloc:
    description: Display choosen player location or if no name set, player location.
    aliases: [loc,location]
    usage: /<command> (|name)
  bal_itemmore:
    description: Sets the amount of items in hand to given amount or 64 if nothing given.
    aliases: more
    usage: /<command> (|amount)
  bal_item:
    description: Gives the player item of choice. You can specify someone else as the player.
    aliases: [i,item]
    usage: /<command> (name|id) [amount] [player] [damage]
  bal_addbl:
    description: BlackList an item
    aliases: [addblacklist,abl]
    usage: /<command> (name|id)
  bal_rmbl:
    description: remove the item from the blackList
    aliases: [rmblacklist,rbl]
    usage: /<command> (name|id)
  bal_itemcolor:
    description: Changes the color of a colorable item in hand.
    aliases: [c,color]
    usage: /<command> (colorname|colorid|help)
  bal_tpto:
    description: Teleports the player to another player.
    aliases: [tp,tpto]
    usage: /<command> (playername)
  bal_tp2p:
    description: Teleports chosen player to another chosen player
    aliases: [tp2p,t2p]
    usage: /<command> (playername from) (palyername to)
  bal_tphere:
    description: Teleports another player to the player.
    aliases: [s,tphere]
    usage: /<command> (playername)
  bal_playermsg:
    description: Sends a private message to another player.
    aliases: [msg,message]
    usage: /<command> (playername) (message text)
  bal_pclear:
    description: clear the inventory of the playername.
    aliases: [pclear,clear]
    usage: /<command> (playername)
  bal_wclear:
    description: clear the inventory of the playername.
    aliases: [wclear,clearw]
    usage: /<command> duration
  bal_wstorm:
    description: clear the inventory of the playername.
    aliases: [wstorm]
    usage: /<command> duration
