name: AdminCmd
main: com.Balor.bukkit.AdminCmd.AdminCmd
version: 4.2.2
author: Plague modded by Balor
description: >
             This plugin implements the basic commands for running a server.
commands:
  bal_timeset:
    description: Set world time to a given timestamp/alias.
    aliases: time
    usage: /<command> day|night|dusk|dawn|<raw>
  bal_timeday:
    description: Short for /time day.
    aliases: day
    usage: /<command>
  bal_playerlist:
    description: Lists all online players.
    aliases: [playerlist,plist]
    usage: /<command>
  bal_repair:
    description: Repair if possible the item in hand.
    aliases: [repair]
    usage: /<command>
  bal_playerloc:
    description: Display choosen player location or if no name set, player location.
    aliases: [loc,location]
    usage: /<command> (|name)
  bal_itemmore:
    description: Sets the amount of items in hand to given amount or 64 if nothing given.
    aliases: more
    usage: /<command> (|amount)
  bal_item:
    description: Gives the player item of choice. You can specify someone else as the player.
    aliases: [i,item]
    usage: /<command> (name|id) [amount] [player] [damage]
  bal_itemcolor:
    description: Changes the color of a colorable item in hand.
    aliases: [c,color]
    usage: /<command> (colorname|colorid|help)
  bal_tpto:
    description: Teleports the player to another player.
    aliases: [tp,tpto]
    usage: /<command> (playername)
  bal_tp2p:
    description: Teleports chosen player to another chosen player
    aliases: [tp2p,t2p]
    usage: /<command> (playername from) (palyername to)
  bal_tphere:
    description: Teleports another player to the player.
    aliases: [s,tphere]
    usage: /<command> (playername)
  bal_playermsg:
    description: Sends a private message to another player.
    aliases: [msg,message]
    usage: /<command> (playername) (message text)
